### ISSUE TITLE
Add building of toolchains targetting windows-x64 and linux-aarch64

### ISSUE THREAD

**Issue by ZacWalk** [ZacWalk/mingw-woarm64-build#36]
We need to make sure we are not causing regressions in those closely related toolchains targetting windows-x64 and linux-aarch64.

Let's add these targets to the advanced build script and actions matrix.

We want this as a simple stop-gap until we upstream and can take advantage of Linaro's CI.

**Comment by taozuhong** [comment]
Building windows-x64 and linux-aarch64 on the ARM platform? or x64 platform?

**Comment by Blackhex** [comment]
@taozuhong So far we are building the toolchain on the default x86 linux GHA runners only as Arm64-ones are not generally available and this ticket should just add the Linux x86 and Windows x86 toolchain targets build variants. Purpose of this workflow is just to detect possible regressions caused by our own changes or by rebasing to the upstream.

@ZacWalk  The "windows-x64" part of this ticket is implemented by https://github.com/ZacWalk/mingw-woarm64-build/pull/41
